<project>
  <path id="project.class.path">
    <pathelement location="build/src"/>
    <pathelement location="lib/junit-4.8.2.jar"/>
  </path>

  <target name="compile" description="compile the code">
    <mkdir dir="build/src" />
    <javac srcdir="src"
      	   destdir="build/src"
      	   includeantruntime="false"
      	   debug="true" >
      <classpath refid="project.class.path" />
    </javac>
  </target>

  <target name="clean" description="clean up the project">
    <delete>
      <fileset dir="build/src" includes="*.class"/>
      <fileset dir="build" includes="*.jar"/>
      <fileset dir="build" includes="*.class"/>
      <fileset dir="lib" includes="NSetCache.jar"/>
    </delete>
  </target>


  <target name="run" depends="compile" description="run the example main">
    <java classname="Example" classpath="build/src"/>
  </target>

  <target name="jar" depends="compile" description="create a jar file">
    <jar destfile="lib/NSetCache.jar">
      <fileset dir="build/src">
        <include name="NSetCache.class"/>
        <include name="CacheLibrary.class"/>
        <include name="CacheItem.class"/>
      </fileset>
    </jar>
  </target>

  <target name="test" depends="compile" description="run JUnit tests">
    <junit haltonerror="no" haltonfailure="no">
      <classpath refid="project.class.path" />
      <batchtest fork="yes">
	<fileset dir="src">
	  <include name="*Test.java"/>
	</fileset>
      </batchtest>
      <formatter type="brief" usefile="false" />
    </junit>
  </target>

</project>
